language: node_js
node_js:
  - "8.1"

branches:
  only:
    - master

sudo: required
dist: trusty

addons:
    chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - ng test --watch false
  - ng e2e
  - ng build --prod --env=prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
