language: node_js
node_js:
  - "11.7.0"

branches:
  only:
    - master

sudo: required
dist: trusty

cache:
  directories:
  - node_modules

addons:
    chrome: stable

before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

install:
  - npm install

script:
  - npm run all_tests
  - ng build --prod --i18n-file src/locale/de/messages.de.xlf --i18n-format xlf --i18n-locale de

after_success:
  - firebase deploy --token $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
